#!/usr/bin/env ruby

def find_originator(r)
  result = `whois -h riswhois.ripe.net " #{r}"`.split(/\n\n/)
  records = []
  result.each do |table|
    record = table.split(/\n/)
    entries = {}   
    record.each do |entry|
      next if entry.match(/^%/)
      next if entry.empty?
      key_value = entry.split(/:/)
      entries[key_value[0].to_sym] = key_value[1]
    end
    records << entries unless entries.empty?
  end
  records.each do |record|
    record.each do |k,v| 
      puts "#{k.to_s}: #{v}\n"
    end
    puts "\n\n"    
  end
end

def query_registry(r)
  result = `whois -h whois.cymru.com " -v #{r}"`.split(/\n/)
  headings = result[0].gsub(/\s+/, '').split(/\|/)
  info = result[1].gsub(/\s+/, '').split(/\|/)
  headings.each_with_index do |v,i|
    puts "%-10s : #{info[i]}\n" % v
  end  
end

route = ARGV[1]
case ARGV[0]
  when "-o"
    find_originator(route)
  when "-q"
    query_registry(route)
  else
    puts <<-EOF
Invalid option.
Usage:
  rinfo <option> [route]

  Options:
    -o  Originating ASN of [route]
    -q  Query route registries for basic information on [route] 
EOF
end